#!/usr/bin/env bash
# Brings up a demo stand of «Автомаляр» on a fresh Ubuntu/Debian server.
#
#   git clone https://github.com/NasimYus/avtomalyar.git && cd avtomalyar
#   sudo ./deploy/install.sh                 # https://<server-ip>.sslip.io
#   sudo ./deploy/install.sh demo.example.tj # your own domain
#   sudo ./deploy/install.sh --no-demo       # empty database, admin only
#
# Safe to run again: secrets are generated once and kept in deploy/.env,
# the database is only seeded when it is empty. After a `git pull` the
# same command rebuilds and restarts with the new code.
set -euo pipefail

cd "$(dirname "$0")"

SITE=""
DEMO=1
for arg in "$@"; do
  case "$arg" in
    --no-demo) DEMO=0 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) SITE="$arg" ;;
  esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# Building the images (Go + the Vite bundle) wants about 2 GB of memory; on
# a smaller server add swap once, or the build gets killed halfway.
MEM_MB="$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)"
if [ "$MEM_MB" -lt 1900 ] && [ "$(swapon --noheadings | wc -l)" -eq 0 ]; then
  say "Памяти ${MEM_MB} МБ — добавляю swap 2 ГБ для сборки…"
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

if ! command -v docker >/dev/null 2>&1; then
  say "Устанавливаю Docker…"
  curl -fsSL https://get.docker.com | sh
fi

if [ ! -f .env ]; then
  say "Создаю deploy/.env с новыми паролями…"
  if [ -z "$SITE" ]; then
    IP="$(curl -fsS4 https://api.ipify.org || hostname -I | awk '{print $1}')"
    SITE="${IP}.sslip.io"
  fi
  secret() { openssl rand -hex "$1"; }
  umask 077
  cat > .env <<ENV
# Generated by install.sh — keep it secret, keep it safe.
SITE_ADDRESS=${SITE}
POSTGRES_PASSWORD=$(secret 16)
JWT_SECRET=$(secret 32)
ADMIN_PASSWORD=$(secret 6)
ENV
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a

say "Собираю и запускаю (первый раз — несколько минут)…"
docker compose up -d --build

say "Жду, пока поднимется API…"
for _ in $(seq 1 60); do
  if docker compose exec -T backend wget -qO /dev/null http://localhost:8080/healthz 2>/dev/null; then
    break
  fi
  sleep 2
done

docker compose exec -T backend seed admin

if [ "$DEMO" = "1" ] && [ ! -f demo-credentials.txt ]; then
  say "Заполняю демо-данными…"
  # Demo dealers' passwords are shown only once, so they are kept here.
  docker compose exec -T backend seed demo | tee demo-credentials.txt
  chmod 600 demo-credentials.txt
fi

case "$SITE_ADDRESS" in
  :80) URL="http://$(hostname -I | awk '{print $1}')" ;;
  :*) URL="http://$(hostname -I | awk '{print $1}')${SITE_ADDRESS}" ;;
  http://*) URL="$SITE_ADDRESS" ;;
  *) URL="https://${SITE_ADDRESS}" ;;
esac

say "Готово."
cat <<DONE
  Адрес:          ${URL}
  Админ:          логин admin, пароль ${ADMIN_PASSWORD}
  Дилеры (демо):  deploy/demo-credentials.txt

  Логи:           cd deploy && docker compose logs -f
  Обновить код:   git pull && sudo ./deploy/install.sh
DONE
