// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (login, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, login, password_hash, name, created_at, updated_at
`

type CreateAdminParams struct {
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Login, arg.PasswordHash, arg.Name)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, login, password_hash, name, created_at, updated_at FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByLogin = `-- name: GetAdminByLogin :one
SELECT id, login, password_hash, name, created_at, updated_at FROM admins WHERE login = $1
`

func (q *Queries) GetAdminByLogin(ctx context.Context, login string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByLogin, login)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
