// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabinet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDealerProfile = `-- name: GetDealerProfile :one
SELECT
    d.id,
    d.full_name,
    d.phone,
    d.login,
    d.is_active,
    d.lifetime_purchase_total,
    d.city_id,
    c.name_ru AS city_name_ru,
    c.name_tg AS city_name_tg,
    d.grade_id,
    g.name_ru AS grade_name_ru,
    g.name_tg AS grade_name_tg,
    g.min_purchase_amount AS grade_min_purchase_amount
FROM dealers d
JOIN cities c ON c.id = d.city_id
LEFT JOIN grades g ON g.id = d.grade_id
WHERE d.id = $1
`

type GetDealerProfileRow struct {
	ID                     int64       `json:"id"`
	FullName               string      `json:"full_name"`
	Phone                  string      `json:"phone"`
	Login                  string      `json:"login"`
	IsActive               bool        `json:"is_active"`
	LifetimePurchaseTotal  int64       `json:"lifetime_purchase_total"`
	CityID                 int64       `json:"city_id"`
	CityNameRu             string      `json:"city_name_ru"`
	CityNameTg             string      `json:"city_name_tg"`
	GradeID                pgtype.Int8 `json:"grade_id"`
	GradeNameRu            pgtype.Text `json:"grade_name_ru"`
	GradeNameTg            pgtype.Text `json:"grade_name_tg"`
	GradeMinPurchaseAmount pgtype.Int8 `json:"grade_min_purchase_amount"`
}

// Everything the cabinet's header needs in one row: the dealer plus the
// names their ids stand for.
func (q *Queries) GetDealerProfile(ctx context.Context, id int64) (GetDealerProfileRow, error) {
	row := q.db.QueryRow(ctx, getDealerProfile, id)
	var i GetDealerProfileRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Login,
		&i.IsActive,
		&i.LifetimePurchaseTotal,
		&i.CityID,
		&i.CityNameRu,
		&i.CityNameTg,
		&i.GradeID,
		&i.GradeNameRu,
		&i.GradeNameTg,
		&i.GradeMinPurchaseAmount,
	)
	return i, err
}

const listDealerPromotions = `-- name: ListDealerPromotions :many
SELECT id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at FROM promotions
WHERE status IN ('active', 'calculated', 'published')
ORDER BY end_date DESC, id DESC
`

// Promotions a dealer may see: the ones running now, the ones whose
// results are being reviewed, and the ones already published. Drafts and
// archived promotions stay out of the cabinet.
//
// Whether the dealer actually takes part is decided by domain.IsEligible,
// not here, so the rule has a single tested implementation.
func (q *Queries) ListDealerPromotions(ctx context.Context) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, listDealerPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promotion{}
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.TitleTg,
			&i.DescriptionRu,
			&i.DescriptionTg,
			&i.StartDate,
			&i.EndDate,
			&i.CityID,
			&i.GradeID,
			&i.MinLifetimePurchaseThreshold,
			&i.Status,
			&i.CalculatedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
