// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cities.sql

package db

import (
	"context"
)

const createCity = `-- name: CreateCity :one
INSERT INTO cities (name_ru, name_tg)
VALUES ($1, $2)
RETURNING id, name_ru, name_tg, created_at, updated_at
`

type CreateCityParams struct {
	NameRu string `json:"name_ru"`
	NameTg string `json:"name_tg"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity, arg.NameRu, arg.NameTg)
	var i City
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCity = `-- name: DeleteCity :execrows
DELETE FROM cities WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCityByID = `-- name: GetCityByID :one
SELECT id, name_ru, name_tg, created_at, updated_at FROM cities WHERE id = $1
`

func (q *Queries) GetCityByID(ctx context.Context, id int64) (City, error) {
	row := q.db.QueryRow(ctx, getCityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT id, name_ru, name_tg, created_at, updated_at FROM cities ORDER BY name_ru
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.NameRu,
			&i.NameTg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET name_ru = $2, name_tg = $3
WHERE id = $1
RETURNING id, name_ru, name_tg, created_at, updated_at
`

type UpdateCityParams struct {
	ID     int64  `json:"id"`
	NameRu string `json:"name_ru"`
	NameTg string `json:"name_tg"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity, arg.ID, arg.NameRu, arg.NameTg)
	var i City
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
