// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardTotals = `-- name: DashboardTotals :one
SELECT
    (SELECT count(*) FROM dealers)::bigint AS dealers_total,
    (SELECT count(*) FROM dealers WHERE dealers.is_active)::bigint AS dealers_active,
    (
        SELECT COALESCE(SUM(purchases.amount), 0) FROM purchases
        WHERE purchases.purchase_date >= $1::date
          AND purchases.purchase_date <= $2::date
    )::bigint AS period_amount,
    (
        SELECT count(*) FROM purchases
        WHERE purchases.purchase_date >= $1::date
          AND purchases.purchase_date <= $2::date
    )::bigint AS period_count,
    (SELECT COALESCE(SUM(dealers.lifetime_purchase_total), 0) FROM dealers)::bigint AS lifetime_total,
    (SELECT count(*) FROM promotions WHERE promotions.status = 'active')::bigint AS promotions_active,
    -- Running promotions whose period is over: these are waiting for the
    -- admin to compute results, and are the ones worth chasing.
    (
        SELECT count(*) FROM promotions
        WHERE promotions.status = 'active'
          AND promotions.end_date < $3::date
    )::bigint AS promotions_awaiting
`

type DashboardTotalsParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	Today    pgtype.Date `json:"today"`
}

type DashboardTotalsRow struct {
	DealersTotal       int64 `json:"dealers_total"`
	DealersActive      int64 `json:"dealers_active"`
	PeriodAmount       int64 `json:"period_amount"`
	PeriodCount        int64 `json:"period_count"`
	LifetimeTotal      int64 `json:"lifetime_total"`
	PromotionsActive   int64 `json:"promotions_active"`
	PromotionsAwaiting int64 `json:"promotions_awaiting"`
}

func (q *Queries) DashboardTotals(ctx context.Context, arg DashboardTotalsParams) (DashboardTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardTotals, arg.DateFrom, arg.DateTo, arg.Today)
	var i DashboardTotalsRow
	err := row.Scan(
		&i.DealersTotal,
		&i.DealersActive,
		&i.PeriodAmount,
		&i.PeriodCount,
		&i.LifetimeTotal,
		&i.PromotionsActive,
		&i.PromotionsAwaiting,
	)
	return i, err
}

const dealerCountsByGrade = `-- name: DealerCountsByGrade :many
SELECT
    g.id,
    g.name_ru,
    g.name_tg,
    g.min_purchase_amount,
    count(d.id)::bigint AS dealers_count
FROM grades g
LEFT JOIN dealers d ON d.grade_id = g.id
GROUP BY g.id
ORDER BY g.min_purchase_amount
`

type DealerCountsByGradeRow struct {
	ID                int64  `json:"id"`
	NameRu            string `json:"name_ru"`
	NameTg            string `json:"name_tg"`
	MinPurchaseAmount int64  `json:"min_purchase_amount"`
	DealersCount      int64  `json:"dealers_count"`
}

func (q *Queries) DealerCountsByGrade(ctx context.Context) ([]DealerCountsByGradeRow, error) {
	rows, err := q.db.Query(ctx, dealerCountsByGrade)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealerCountsByGradeRow{}
	for rows.Next() {
		var i DealerCountsByGradeRow
		if err := rows.Scan(
			&i.ID,
			&i.NameRu,
			&i.NameTg,
			&i.MinPurchaseAmount,
			&i.DealersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
