// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dealers.sql

package db

import (
	"context"
)

const getDealerByID = `-- name: GetDealerByID :one
SELECT id, full_name, phone, city_id, grade_id, lifetime_purchase_total, login, password_hash, is_active, created_at, updated_at FROM dealers WHERE id = $1
`

func (q *Queries) GetDealerByID(ctx context.Context, id int64) (Dealer, error) {
	row := q.db.QueryRow(ctx, getDealerByID, id)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CityID,
		&i.GradeID,
		&i.LifetimePurchaseTotal,
		&i.Login,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealerByLogin = `-- name: GetDealerByLogin :one
SELECT id, full_name, phone, city_id, grade_id, lifetime_purchase_total, login, password_hash, is_active, created_at, updated_at FROM dealers WHERE login = $1
`

func (q *Queries) GetDealerByLogin(ctx context.Context, login string) (Dealer, error) {
	row := q.db.QueryRow(ctx, getDealerByLogin, login)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CityID,
		&i.GradeID,
		&i.LifetimePurchaseTotal,
		&i.Login,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
