// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGrade = `-- name: CreateGrade :one
INSERT INTO grades (name_ru, name_tg, min_purchase_amount, color)
VALUES ($1, $2, $3, $4)
RETURNING id, name_ru, name_tg, min_purchase_amount, created_at, updated_at, color
`

type CreateGradeParams struct {
	NameRu            string      `json:"name_ru"`
	NameTg            string      `json:"name_tg"`
	MinPurchaseAmount int64       `json:"min_purchase_amount"`
	Color             pgtype.Text `json:"color"`
}

func (q *Queries) CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, createGrade,
		arg.NameRu,
		arg.NameTg,
		arg.MinPurchaseAmount,
		arg.Color,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.MinPurchaseAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
	)
	return i, err
}

const deleteGrade = `-- name: DeleteGrade :execrows
DELETE FROM grades WHERE id = $1
`

func (q *Queries) DeleteGrade(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGradeByID = `-- name: GetGradeByID :one
SELECT id, name_ru, name_tg, min_purchase_amount, created_at, updated_at, color FROM grades WHERE id = $1
`

func (q *Queries) GetGradeByID(ctx context.Context, id int64) (Grade, error) {
	row := q.db.QueryRow(ctx, getGradeByID, id)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.MinPurchaseAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
	)
	return i, err
}

const listGrades = `-- name: ListGrades :many
SELECT id, name_ru, name_tg, min_purchase_amount, created_at, updated_at, color FROM grades ORDER BY min_purchase_amount
`

func (q *Queries) ListGrades(ctx context.Context) ([]Grade, error) {
	rows, err := q.db.Query(ctx, listGrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grade{}
	for rows.Next() {
		var i Grade
		if err := rows.Scan(
			&i.ID,
			&i.NameRu,
			&i.NameTg,
			&i.MinPurchaseAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeAllDealerGrades = `-- name: RecomputeAllDealerGrades :exec
UPDATE dealers d
SET grade_id = (
    SELECT g.id
    FROM grades g
    WHERE g.min_purchase_amount <= d.lifetime_purchase_total
    ORDER BY g.min_purchase_amount DESC
    LIMIT 1
)
WHERE d.grade_id IS DISTINCT FROM (
    SELECT g.id
    FROM grades g
    WHERE g.min_purchase_amount <= d.lifetime_purchase_total
    ORDER BY g.min_purchase_amount DESC
    LIMIT 1
)
`

func (q *Queries) RecomputeAllDealerGrades(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recomputeAllDealerGrades)
	return err
}

const updateGrade = `-- name: UpdateGrade :one
UPDATE grades
SET name_ru = $2, name_tg = $3, min_purchase_amount = $4, color = $5
WHERE id = $1
RETURNING id, name_ru, name_tg, min_purchase_amount, created_at, updated_at, color
`

type UpdateGradeParams struct {
	ID                int64       `json:"id"`
	NameRu            string      `json:"name_ru"`
	NameTg            string      `json:"name_tg"`
	MinPurchaseAmount int64       `json:"min_purchase_amount"`
	Color             pgtype.Text `json:"color"`
}

func (q *Queries) UpdateGrade(ctx context.Context, arg UpdateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, updateGrade,
		arg.ID,
		arg.NameRu,
		arg.NameTg,
		arg.MinPurchaseAmount,
		arg.Color,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.MinPurchaseAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
	)
	return i, err
}
