// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           int64              `json:"id"`
	Login        string             `json:"login"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type City struct {
	ID        int64              `json:"id"`
	NameRu    string             `json:"name_ru"`
	NameTg    string             `json:"name_tg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Dealer struct {
	ID                    int64              `json:"id"`
	FullName              string             `json:"full_name"`
	Phone                 string             `json:"phone"`
	CityID                int64              `json:"city_id"`
	GradeID               pgtype.Int8        `json:"grade_id"`
	LifetimePurchaseTotal int64              `json:"lifetime_purchase_total"`
	Login                 string             `json:"login"`
	PasswordHash          string             `json:"password_hash"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Grade struct {
	ID                int64              `json:"id"`
	NameRu            string             `json:"name_ru"`
	NameTg            string             `json:"name_tg"`
	MinPurchaseAmount int64              `json:"min_purchase_amount"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Color             pgtype.Text        `json:"color"`
}

type Prize struct {
	ID            int64              `json:"id"`
	NameRu        string             `json:"name_ru"`
	NameTg        string             `json:"name_tg"`
	DescriptionRu pgtype.Text        `json:"description_ru"`
	DescriptionTg pgtype.Text        `json:"description_tg"`
	PhotoPath     pgtype.Text        `json:"photo_path"`
	StockQuantity pgtype.Int4        `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Promotion struct {
	ID                           int64              `json:"id"`
	TitleRu                      string             `json:"title_ru"`
	TitleTg                      string             `json:"title_tg"`
	DescriptionRu                pgtype.Text        `json:"description_ru"`
	DescriptionTg                pgtype.Text        `json:"description_tg"`
	StartDate                    pgtype.Date        `json:"start_date"`
	EndDate                      pgtype.Date        `json:"end_date"`
	CityID                       pgtype.Int8        `json:"city_id"`
	GradeID                      pgtype.Int8        `json:"grade_id"`
	MinLifetimePurchaseThreshold pgtype.Int8        `json:"min_lifetime_purchase_threshold"`
	Status                       string             `json:"status"`
	CalculatedAt                 pgtype.Timestamptz `json:"calculated_at"`
	PublishedAt                  pgtype.Timestamptz `json:"published_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type PromotionPrizePlace struct {
	ID          int64              `json:"id"`
	PromotionID int64              `json:"promotion_id"`
	PlaceRank   int32              `json:"place_rank"`
	PrizeID     int64              `json:"prize_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PromotionResult struct {
	ID                 int64              `json:"id"`
	PromotionID        int64              `json:"promotion_id"`
	DealerID           int64              `json:"dealer_id"`
	PeriodTotal        int64              `json:"period_total"`
	PlaceRank          pgtype.Int4        `json:"place_rank"`
	PrizeID            pgtype.Int8        `json:"prize_id"`
	IsManuallyAdjusted bool               `json:"is_manually_adjusted"`
	Awarded            bool               `json:"awarded"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Purchase struct {
	ID           int64              `json:"id"`
	DealerID     int64              `json:"dealer_id"`
	Amount       int64              `json:"amount"`
	PurchaseDate pgtype.Date        `json:"purchase_date"`
	Comment      pgtype.Text        `json:"comment"`
	CreatedBy    int64              `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
