// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           int64              `json:"id"`
	Login        string             `json:"login"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type City struct {
	ID        int64              `json:"id"`
	NameRu    string             `json:"name_ru"`
	NameTg    string             `json:"name_tg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Dealer struct {
	ID                    int64              `json:"id"`
	FullName              string             `json:"full_name"`
	Phone                 string             `json:"phone"`
	CityID                int64              `json:"city_id"`
	GradeID               pgtype.Int8        `json:"grade_id"`
	LifetimePurchaseTotal int64              `json:"lifetime_purchase_total"`
	Login                 string             `json:"login"`
	PasswordHash          string             `json:"password_hash"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Grade struct {
	ID                int64              `json:"id"`
	NameRu            string             `json:"name_ru"`
	NameTg            string             `json:"name_tg"`
	MinPurchaseAmount int64              `json:"min_purchase_amount"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Prize struct {
	ID            int64              `json:"id"`
	NameRu        string             `json:"name_ru"`
	NameTg        string             `json:"name_tg"`
	DescriptionRu pgtype.Text        `json:"description_ru"`
	DescriptionTg pgtype.Text        `json:"description_tg"`
	PhotoPath     pgtype.Text        `json:"photo_path"`
	StockQuantity pgtype.Int4        `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Purchase struct {
	ID           int64              `json:"id"`
	DealerID     int64              `json:"dealer_id"`
	Amount       int64              `json:"amount"`
	PurchaseDate pgtype.Date        `json:"purchase_date"`
	Comment      pgtype.Text        `json:"comment"`
	CreatedBy    int64              `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
