// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prizes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrize = `-- name: CreatePrize :one
INSERT INTO prizes (name_ru, name_tg, description_ru, description_tg, stock_quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name_ru, name_tg, description_ru, description_tg, photo_path, stock_quantity, created_at, updated_at
`

type CreatePrizeParams struct {
	NameRu        string      `json:"name_ru"`
	NameTg        string      `json:"name_tg"`
	DescriptionRu pgtype.Text `json:"description_ru"`
	DescriptionTg pgtype.Text `json:"description_tg"`
	StockQuantity pgtype.Int4 `json:"stock_quantity"`
}

func (q *Queries) CreatePrize(ctx context.Context, arg CreatePrizeParams) (Prize, error) {
	row := q.db.QueryRow(ctx, createPrize,
		arg.NameRu,
		arg.NameTg,
		arg.DescriptionRu,
		arg.DescriptionTg,
		arg.StockQuantity,
	)
	var i Prize
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.PhotoPath,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePrize = `-- name: DeletePrize :execrows
DELETE FROM prizes WHERE id = $1
`

func (q *Queries) DeletePrize(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrize, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPrizeByID = `-- name: GetPrizeByID :one
SELECT id, name_ru, name_tg, description_ru, description_tg, photo_path, stock_quantity, created_at, updated_at FROM prizes WHERE id = $1
`

func (q *Queries) GetPrizeByID(ctx context.Context, id int64) (Prize, error) {
	row := q.db.QueryRow(ctx, getPrizeByID, id)
	var i Prize
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.PhotoPath,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrizes = `-- name: ListPrizes :many
SELECT id, name_ru, name_tg, description_ru, description_tg, photo_path, stock_quantity, created_at, updated_at FROM prizes ORDER BY name_ru
`

func (q *Queries) ListPrizes(ctx context.Context) ([]Prize, error) {
	rows, err := q.db.Query(ctx, listPrizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prize{}
	for rows.Next() {
		var i Prize
		if err := rows.Scan(
			&i.ID,
			&i.NameRu,
			&i.NameTg,
			&i.DescriptionRu,
			&i.DescriptionTg,
			&i.PhotoPath,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrize = `-- name: UpdatePrize :one
UPDATE prizes
SET name_ru = $2, name_tg = $3, description_ru = $4, description_tg = $5, stock_quantity = $6
WHERE id = $1
RETURNING id, name_ru, name_tg, description_ru, description_tg, photo_path, stock_quantity, created_at, updated_at
`

type UpdatePrizeParams struct {
	ID            int64       `json:"id"`
	NameRu        string      `json:"name_ru"`
	NameTg        string      `json:"name_tg"`
	DescriptionRu pgtype.Text `json:"description_ru"`
	DescriptionTg pgtype.Text `json:"description_tg"`
	StockQuantity pgtype.Int4 `json:"stock_quantity"`
}

func (q *Queries) UpdatePrize(ctx context.Context, arg UpdatePrizeParams) (Prize, error) {
	row := q.db.QueryRow(ctx, updatePrize,
		arg.ID,
		arg.NameRu,
		arg.NameTg,
		arg.DescriptionRu,
		arg.DescriptionTg,
		arg.StockQuantity,
	)
	var i Prize
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.PhotoPath,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePrizePhoto = `-- name: UpdatePrizePhoto :one
UPDATE prizes
SET photo_path = $2
WHERE id = $1
RETURNING id, name_ru, name_tg, description_ru, description_tg, photo_path, stock_quantity, created_at, updated_at
`

type UpdatePrizePhotoParams struct {
	ID        int64       `json:"id"`
	PhotoPath pgtype.Text `json:"photo_path"`
}

func (q *Queries) UpdatePrizePhoto(ctx context.Context, arg UpdatePrizePhotoParams) (Prize, error) {
	row := q.db.QueryRow(ctx, updatePrizePhoto, arg.ID, arg.PhotoPath)
	var i Prize
	err := row.Scan(
		&i.ID,
		&i.NameRu,
		&i.NameTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.PhotoPath,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
