// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPromotionsByStatus = `-- name: CountPromotionsByStatus :many
SELECT status, count(*)::bigint AS total FROM promotions GROUP BY status
`

type CountPromotionsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountPromotionsByStatus(ctx context.Context) ([]CountPromotionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countPromotionsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPromotionsByStatusRow{}
	for rows.Next() {
		var i CountPromotionsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPrizePlace = `-- name: CreatePrizePlace :one
INSERT INTO promotion_prize_places (promotion_id, place_rank, prize_id)
VALUES ($1, $2, $3)
RETURNING id, promotion_id, place_rank, prize_id, created_at, updated_at
`

type CreatePrizePlaceParams struct {
	PromotionID int64 `json:"promotion_id"`
	PlaceRank   int32 `json:"place_rank"`
	PrizeID     int64 `json:"prize_id"`
}

func (q *Queries) CreatePrizePlace(ctx context.Context, arg CreatePrizePlaceParams) (PromotionPrizePlace, error) {
	row := q.db.QueryRow(ctx, createPrizePlace, arg.PromotionID, arg.PlaceRank, arg.PrizeID)
	var i PromotionPrizePlace
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.PlaceRank,
		&i.PrizeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO promotions (
    title_ru, title_tg, description_ru, description_tg,
    start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at
`

type CreatePromotionParams struct {
	TitleRu                      string      `json:"title_ru"`
	TitleTg                      string      `json:"title_tg"`
	DescriptionRu                pgtype.Text `json:"description_ru"`
	DescriptionTg                pgtype.Text `json:"description_tg"`
	StartDate                    pgtype.Date `json:"start_date"`
	EndDate                      pgtype.Date `json:"end_date"`
	CityID                       pgtype.Int8 `json:"city_id"`
	GradeID                      pgtype.Int8 `json:"grade_id"`
	MinLifetimePurchaseThreshold pgtype.Int8 `json:"min_lifetime_purchase_threshold"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, createPromotion,
		arg.TitleRu,
		arg.TitleTg,
		arg.DescriptionRu,
		arg.DescriptionTg,
		arg.StartDate,
		arg.EndDate,
		arg.CityID,
		arg.GradeID,
		arg.MinLifetimePurchaseThreshold,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.StartDate,
		&i.EndDate,
		&i.CityID,
		&i.GradeID,
		&i.MinLifetimePurchaseThreshold,
		&i.Status,
		&i.CalculatedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromotionResult = `-- name: CreatePromotionResult :exec
INSERT INTO promotion_results (promotion_id, dealer_id, period_total, place_rank, prize_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePromotionResultParams struct {
	PromotionID int64       `json:"promotion_id"`
	DealerID    int64       `json:"dealer_id"`
	PeriodTotal int64       `json:"period_total"`
	PlaceRank   pgtype.Int4 `json:"place_rank"`
	PrizeID     pgtype.Int8 `json:"prize_id"`
}

func (q *Queries) CreatePromotionResult(ctx context.Context, arg CreatePromotionResultParams) error {
	_, err := q.db.Exec(ctx, createPromotionResult,
		arg.PromotionID,
		arg.DealerID,
		arg.PeriodTotal,
		arg.PlaceRank,
		arg.PrizeID,
	)
	return err
}

const deletePrizePlaces = `-- name: DeletePrizePlaces :exec
DELETE FROM promotion_prize_places WHERE promotion_id = $1
`

func (q *Queries) DeletePrizePlaces(ctx context.Context, promotionID int64) error {
	_, err := q.db.Exec(ctx, deletePrizePlaces, promotionID)
	return err
}

const deletePromotion = `-- name: DeletePromotion :execrows
DELETE FROM promotions WHERE id = $1
`

func (q *Queries) DeletePromotion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePromotion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePromotionResults = `-- name: DeletePromotionResults :exec
DELETE FROM promotion_results WHERE promotion_id = $1
`

func (q *Queries) DeletePromotionResults(ctx context.Context, promotionID int64) error {
	_, err := q.db.Exec(ctx, deletePromotionResults, promotionID)
	return err
}

const getPromotionByID = `-- name: GetPromotionByID :one
SELECT id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at FROM promotions WHERE id = $1
`

func (q *Queries) GetPromotionByID(ctx context.Context, id int64) (Promotion, error) {
	row := q.db.QueryRow(ctx, getPromotionByID, id)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.StartDate,
		&i.EndDate,
		&i.CityID,
		&i.GradeID,
		&i.MinLifetimePurchaseThreshold,
		&i.Status,
		&i.CalculatedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromotionResult = `-- name: GetPromotionResult :one
SELECT id, promotion_id, dealer_id, period_total, place_rank, prize_id, is_manually_adjusted, awarded, created_at, updated_at FROM promotion_results WHERE promotion_id = $1 AND dealer_id = $2
`

type GetPromotionResultParams struct {
	PromotionID int64 `json:"promotion_id"`
	DealerID    int64 `json:"dealer_id"`
}

func (q *Queries) GetPromotionResult(ctx context.Context, arg GetPromotionResultParams) (PromotionResult, error) {
	row := q.db.QueryRow(ctx, getPromotionResult, arg.PromotionID, arg.DealerID)
	var i PromotionResult
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.DealerID,
		&i.PeriodTotal,
		&i.PlaceRank,
		&i.PrizeID,
		&i.IsManuallyAdjusted,
		&i.Awarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDealersWithPeriodTotals = `-- name: ListActiveDealersWithPeriodTotals :many
SELECT
    d.id AS dealer_id,
    d.full_name AS dealer_name,
    d.city_id,
    d.grade_id,
    d.lifetime_purchase_total,
    COALESCE(SUM(p.amount), 0)::bigint AS period_total,
    MAX(p.purchase_date)::date AS last_purchase_date,
    MAX(p.created_at)::timestamptz AS last_purchase_created_at
FROM dealers d
LEFT JOIN purchases p
    ON p.dealer_id = d.id
   AND p.purchase_date >= $1::date
   AND p.purchase_date <= $2::date
WHERE d.is_active
GROUP BY d.id
`

type ListActiveDealersWithPeriodTotalsParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ListActiveDealersWithPeriodTotalsRow struct {
	DealerID              int64              `json:"dealer_id"`
	DealerName            string             `json:"dealer_name"`
	CityID                int64              `json:"city_id"`
	GradeID               pgtype.Int8        `json:"grade_id"`
	LifetimePurchaseTotal int64              `json:"lifetime_purchase_total"`
	PeriodTotal           int64              `json:"period_total"`
	LastPurchaseDate      pgtype.Date        `json:"last_purchase_date"`
	LastPurchaseCreatedAt pgtype.Timestamptz `json:"last_purchase_created_at"`
}

// Period totals for every active dealer, including those who bought
// nothing in the window (they still take part, with a total of 0).
// Eligibility filters are deliberately left to domain.IsEligible so the
// rule has a single, tested implementation; the dealer count is in the
// hundreds, so loading them all is fine.
func (q *Queries) ListActiveDealersWithPeriodTotals(ctx context.Context, arg ListActiveDealersWithPeriodTotalsParams) ([]ListActiveDealersWithPeriodTotalsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDealersWithPeriodTotals, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDealersWithPeriodTotalsRow{}
	for rows.Next() {
		var i ListActiveDealersWithPeriodTotalsRow
		if err := rows.Scan(
			&i.DealerID,
			&i.DealerName,
			&i.CityID,
			&i.GradeID,
			&i.LifetimePurchaseTotal,
			&i.PeriodTotal,
			&i.LastPurchaseDate,
			&i.LastPurchaseCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrizePlaces = `-- name: ListPrizePlaces :many
SELECT pp.id, pp.promotion_id, pp.place_rank, pp.prize_id, pp.created_at, pp.updated_at, pr.name_ru AS prize_name_ru, pr.name_tg AS prize_name_tg, pr.photo_path AS prize_photo_path
FROM promotion_prize_places pp
JOIN prizes pr ON pr.id = pp.prize_id
WHERE pp.promotion_id = $1
ORDER BY pp.place_rank
`

type ListPrizePlacesRow struct {
	ID             int64              `json:"id"`
	PromotionID    int64              `json:"promotion_id"`
	PlaceRank      int32              `json:"place_rank"`
	PrizeID        int64              `json:"prize_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PrizeNameRu    string             `json:"prize_name_ru"`
	PrizeNameTg    string             `json:"prize_name_tg"`
	PrizePhotoPath pgtype.Text        `json:"prize_photo_path"`
}

func (q *Queries) ListPrizePlaces(ctx context.Context, promotionID int64) ([]ListPrizePlacesRow, error) {
	rows, err := q.db.Query(ctx, listPrizePlaces, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrizePlacesRow{}
	for rows.Next() {
		var i ListPrizePlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.PlaceRank,
			&i.PrizeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrizeNameRu,
			&i.PrizeNameTg,
			&i.PrizePhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionResults = `-- name: ListPromotionResults :many
SELECT
    r.id, r.promotion_id, r.dealer_id, r.period_total, r.place_rank, r.prize_id, r.is_manually_adjusted, r.awarded, r.created_at, r.updated_at,
    d.full_name AS dealer_name,
    d.city_id AS dealer_city_id,
    c.name_ru AS dealer_city_ru,
    c.name_tg AS dealer_city_tg,
    pr.name_ru AS prize_name_ru,
    pr.name_tg AS prize_name_tg
FROM promotion_results r
JOIN dealers d ON d.id = r.dealer_id
JOIN cities c ON c.id = d.city_id
LEFT JOIN prizes pr ON pr.id = r.prize_id
WHERE r.promotion_id = $1
ORDER BY r.place_rank NULLS LAST, r.period_total DESC, r.dealer_id
`

type ListPromotionResultsRow struct {
	ID                 int64              `json:"id"`
	PromotionID        int64              `json:"promotion_id"`
	DealerID           int64              `json:"dealer_id"`
	PeriodTotal        int64              `json:"period_total"`
	PlaceRank          pgtype.Int4        `json:"place_rank"`
	PrizeID            pgtype.Int8        `json:"prize_id"`
	IsManuallyAdjusted bool               `json:"is_manually_adjusted"`
	Awarded            bool               `json:"awarded"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DealerName         string             `json:"dealer_name"`
	DealerCityID       int64              `json:"dealer_city_id"`
	DealerCityRu       string             `json:"dealer_city_ru"`
	DealerCityTg       string             `json:"dealer_city_tg"`
	PrizeNameRu        pgtype.Text        `json:"prize_name_ru"`
	PrizeNameTg        pgtype.Text        `json:"prize_name_tg"`
}

func (q *Queries) ListPromotionResults(ctx context.Context, promotionID int64) ([]ListPromotionResultsRow, error) {
	rows, err := q.db.Query(ctx, listPromotionResults, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromotionResultsRow{}
	for rows.Next() {
		var i ListPromotionResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.DealerID,
			&i.PeriodTotal,
			&i.PlaceRank,
			&i.PrizeID,
			&i.IsManuallyAdjusted,
			&i.Awarded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DealerName,
			&i.DealerCityID,
			&i.DealerCityRu,
			&i.DealerCityTg,
			&i.PrizeNameRu,
			&i.PrizeNameTg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotions = `-- name: ListPromotions :many
SELECT id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at FROM promotions
WHERE ($1::text IS NULL OR status = $1)
ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListPromotions(ctx context.Context, status pgtype.Text) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, listPromotions, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promotion{}
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.TitleTg,
			&i.DescriptionRu,
			&i.DescriptionTg,
			&i.StartDate,
			&i.EndDate,
			&i.CityID,
			&i.GradeID,
			&i.MinLifetimePurchaseThreshold,
			&i.Status,
			&i.CalculatedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPromotionStatus = `-- name: SetPromotionStatus :one
UPDATE promotions
SET status = $2,
    calculated_at = CASE WHEN $2 = 'calculated' THEN now() ELSE calculated_at END,
    published_at = CASE WHEN $2 = 'published' THEN now() ELSE published_at END
WHERE id = $1
RETURNING id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at
`

type SetPromotionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetPromotionStatus(ctx context.Context, arg SetPromotionStatusParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, setPromotionStatus, arg.ID, arg.Status)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.StartDate,
		&i.EndDate,
		&i.CityID,
		&i.GradeID,
		&i.MinLifetimePurchaseThreshold,
		&i.Status,
		&i.CalculatedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromotion = `-- name: UpdatePromotion :one
UPDATE promotions
SET title_ru = $2,
    title_tg = $3,
    description_ru = $4,
    description_tg = $5,
    start_date = $6,
    end_date = $7,
    city_id = $8,
    grade_id = $9,
    min_lifetime_purchase_threshold = $10
WHERE id = $1
RETURNING id, title_ru, title_tg, description_ru, description_tg, start_date, end_date, city_id, grade_id, min_lifetime_purchase_threshold, status, calculated_at, published_at, created_at, updated_at
`

type UpdatePromotionParams struct {
	ID                           int64       `json:"id"`
	TitleRu                      string      `json:"title_ru"`
	TitleTg                      string      `json:"title_tg"`
	DescriptionRu                pgtype.Text `json:"description_ru"`
	DescriptionTg                pgtype.Text `json:"description_tg"`
	StartDate                    pgtype.Date `json:"start_date"`
	EndDate                      pgtype.Date `json:"end_date"`
	CityID                       pgtype.Int8 `json:"city_id"`
	GradeID                      pgtype.Int8 `json:"grade_id"`
	MinLifetimePurchaseThreshold pgtype.Int8 `json:"min_lifetime_purchase_threshold"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, updatePromotion,
		arg.ID,
		arg.TitleRu,
		arg.TitleTg,
		arg.DescriptionRu,
		arg.DescriptionTg,
		arg.StartDate,
		arg.EndDate,
		arg.CityID,
		arg.GradeID,
		arg.MinLifetimePurchaseThreshold,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleTg,
		&i.DescriptionRu,
		&i.DescriptionTg,
		&i.StartDate,
		&i.EndDate,
		&i.CityID,
		&i.GradeID,
		&i.MinLifetimePurchaseThreshold,
		&i.Status,
		&i.CalculatedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromotionResult = `-- name: UpdatePromotionResult :one
UPDATE promotion_results
SET place_rank = $3,
    prize_id = $4,
    awarded = $5,
    is_manually_adjusted = true
WHERE promotion_id = $1 AND dealer_id = $2
RETURNING id, promotion_id, dealer_id, period_total, place_rank, prize_id, is_manually_adjusted, awarded, created_at, updated_at
`

type UpdatePromotionResultParams struct {
	PromotionID int64       `json:"promotion_id"`
	DealerID    int64       `json:"dealer_id"`
	PlaceRank   pgtype.Int4 `json:"place_rank"`
	PrizeID     pgtype.Int8 `json:"prize_id"`
	Awarded     bool        `json:"awarded"`
}

// Manual correction before publication: an admin can move a dealer off a
// prize place or swap the prize; the row is flagged so the change is
// visible afterwards.
func (q *Queries) UpdatePromotionResult(ctx context.Context, arg UpdatePromotionResultParams) (PromotionResult, error) {
	row := q.db.QueryRow(ctx, updatePromotionResult,
		arg.PromotionID,
		arg.DealerID,
		arg.PlaceRank,
		arg.PrizeID,
		arg.Awarded,
	)
	var i PromotionResult
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.DealerID,
		&i.PeriodTotal,
		&i.PlaceRank,
		&i.PrizeID,
		&i.IsManuallyAdjusted,
		&i.Awarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
