// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPurchases = `-- name: CountPurchases :one
SELECT count(*) FROM purchases
WHERE ($1::bigint IS NULL OR dealer_id = $1)
  AND ($2::date IS NULL OR purchase_date >= $2)
  AND ($3::date IS NULL OR purchase_date <= $3)
`

type CountPurchasesParams struct {
	DealerID pgtype.Int8 `json:"dealer_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

func (q *Queries) CountPurchases(ctx context.Context, arg CountPurchasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchases, arg.DealerID, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (dealer_id, amount, purchase_date, comment, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, dealer_id, amount, purchase_date, comment, created_by, created_at, updated_at
`

type CreatePurchaseParams struct {
	DealerID     int64       `json:"dealer_id"`
	Amount       int64       `json:"amount"`
	PurchaseDate pgtype.Date `json:"purchase_date"`
	Comment      pgtype.Text `json:"comment"`
	CreatedBy    int64       `json:"created_by"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.DealerID,
		arg.Amount,
		arg.PurchaseDate,
		arg.Comment,
		arg.CreatedBy,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Amount,
		&i.PurchaseDate,
		&i.Comment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePurchase = `-- name: DeletePurchase :execrows
DELETE FROM purchases WHERE id = $1
`

func (q *Queries) DeletePurchase(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurchase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPurchaseByID = `-- name: GetPurchaseByID :one
SELECT id, dealer_id, amount, purchase_date, comment, created_by, created_at, updated_at FROM purchases WHERE id = $1
`

func (q *Queries) GetPurchaseByID(ctx context.Context, id int64) (Purchase, error) {
	row := q.db.QueryRow(ctx, getPurchaseByID, id)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Amount,
		&i.PurchaseDate,
		&i.Comment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurchases = `-- name: ListPurchases :many
SELECT id, dealer_id, amount, purchase_date, comment, created_by, created_at, updated_at FROM purchases
WHERE ($1::bigint IS NULL OR dealer_id = $1)
  AND ($2::date IS NULL OR purchase_date >= $2)
  AND ($3::date IS NULL OR purchase_date <= $3)
ORDER BY purchase_date DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListPurchasesParams struct {
	DealerID pgtype.Int8 `json:"dealer_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, listPurchases,
		arg.DealerID,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Purchase{}
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Amount,
			&i.PurchaseDate,
			&i.Comment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeDealerLifetimeTotal = `-- name: RecomputeDealerLifetimeTotal :exec
UPDATE dealers
SET lifetime_purchase_total = (
    SELECT COALESCE(SUM(amount), 0) FROM purchases WHERE dealer_id = $1
)
WHERE id = $1
`

func (q *Queries) RecomputeDealerLifetimeTotal(ctx context.Context, dealerID int64) error {
	_, err := q.db.Exec(ctx, recomputeDealerLifetimeTotal, dealerID)
	return err
}

const updatePurchase = `-- name: UpdatePurchase :one
UPDATE purchases
SET dealer_id = $2, amount = $3, purchase_date = $4, comment = $5
WHERE id = $1
RETURNING id, dealer_id, amount, purchase_date, comment, created_by, created_at, updated_at
`

type UpdatePurchaseParams struct {
	ID           int64       `json:"id"`
	DealerID     int64       `json:"dealer_id"`
	Amount       int64       `json:"amount"`
	PurchaseDate pgtype.Date `json:"purchase_date"`
	Comment      pgtype.Text `json:"comment"`
}

func (q *Queries) UpdatePurchase(ctx context.Context, arg UpdatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, updatePurchase,
		arg.ID,
		arg.DealerID,
		arg.Amount,
		arg.PurchaseDate,
		arg.Comment,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Amount,
		&i.PurchaseDate,
		&i.Comment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
